import localFont from "next/font/local";
import '../../globals.css'
import LandingNavBar from "@/components/LandingNavBar";
import LandingFooter from "@/components/LandingFooter";
import PolicyNav from "@/components/PolicyNav";

const geistSans = localFont({
    src: "../../fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
  });
  const geistMono = localFont({
    src: "../../fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
  });


export const metadata = {
  title: "Task Bank",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav>
          <LandingNavBar/>
        </nav>
        <PolicyNav/>
        {children}
        <LandingFooter/>
      </body>
    </html>
  );
}
